# Generated by Django 5.0.6 on 2024-05-15 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_Code', models.CharField(max_length=100)),
                ('Roll_No', models.CharField(max_length=100)),
                ('Registration_number', models.IntegerField(null=True)),
                ('Name_of_the_Candidate', models.CharField(max_length=100)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('DOB', models.DateField(default=datetime.date(2001, 1, 21))),
                ('Name_of_the_training_Partner', models.CharField(max_length=200)),
                ('Code_of_the_training_Partner', models.CharField(max_length=200)),
                ('Practical1', models.CharField(max_length=100)),
                ('Practical2', models.CharField(max_length=100)),
                ('Internal_Assessment', models.IntegerField(null=True)),
                ('Project', models.CharField(max_length=100)),
                ('Major_Project', models.CharField(default='NA', max_length=100)),
                ('Date_of_Exam', models.DateField(default=datetime.date(2003, 3, 22))),
            ],
        ),
    ]
