# Generated by Django 5.0.6 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='Course_Name',
            field=models.CharField(default='certified computer application accounting and publishing', max_length=100, null=True),
        ),
    ]
