# Generated by Django 5.0.6 on 2024-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tp_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='Cat',
            field=models.CharField(default='X', max_length=100),
        ),
        migrations.AddField(
            model_name='tp',
            name='Major_Project2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='tp',
            name='Theory1',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='tp',
            name='Theory2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='tp',
            name='Total',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='tp',
            name='Typing_Speed',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
