# Generated by Django 5.0.6 on 2024-05-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_tp_cat_tp_major_project2_tp_theory1_tp_theory2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tp',
            name='Date_of_Exam',
            field=models.DateField(null=True),
        ),
    ]
